### ISSUE TITLE
possibly undefined macro: AC_MSG_ERROR

### ISSUE THREAD

**Issue by jegb** [virtual-coin/wolf-cpuminer-multi#2]
If this token and others are legitimate, please use m4_pattern_allow.
See the Autoconf documentation.

Could you help with build instructions?

**Comment by jegb** [comment]
run autogen with sudo

**Comment by ssmmtt** [comment]
Wow, solve my problem, 谢谢！

**Comment by ssmmtt** [comment]
root user also need to add sudo.
